name: Test and Build

on:
  pull_request:
    branches: [develop, main]

jobs:
  test_api:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@master
        id: changed-api
        with:
          paths: apps/api

      - name: Setup PostgreSQL
        if: steps.changed-api.outputs.changed == 'true'
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 10-alpine
          postgresql db: sklep_test
          postgresql user: postgres
          postgresql password: sklep

      - name: Read .nvmrc
        if: steps.changed-api.outputs.changed == 'true'
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js
        if: steps.changed-api.outputs.changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Get yarn cache directory path
        if: steps.changed-api.outputs.changed == 'true'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js modules
        if: steps.changed-api.outputs.changed == 'true'
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.OS }}-

      - name: Install dependencies
        if: steps.changed-api.outputs.changed == 'true'
        run: yarn workspace api install --frozen-lockfile

      - name: Run tsc
        if: steps.changed-api.outputs.changed == 'true'
        run: yarn workspace api tsc

      - name: Run tests
        if: steps.changed-api.outputs.changed == 'true'
        run: yarn workspace api test

      - name: Run eslint
        if: steps.changed-api.outputs.changed == 'true'
        run: yarn workspace api eslint
